name: Ubuntu

on:
  push:
    branches:
        - '*'
  pull_request:
    branches: [ master-dev ]

jobs:
  build:
    if: github.repository_owner == 'grame-cncm' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install libmicrohttpd
      run: |
        sudo apt-get update -qq
        sudo apt-get install libmicrohttpd-dev

    - name: Build Faust
      run: make

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}

    - name: Run impulse tests (C++)
      run: cd tests/impulse-tests && make cpp

    - name: Run impulse tests (Rust)
      run: cd tests/impulse-tests && make rust
